require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/reserves", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Reserve. As you add validations to Reserve, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Reserve.create! valid_attributes
      get reserves_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      reserve = Reserve.create! valid_attributes
      get reserf_url(reserve)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_reserf_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      reserve = Reserve.create! valid_attributes
      get edit_reserf_url(reserve)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Reserve" do
        expect {
          post reserves_url, params: { reserf: valid_attributes }
        }.to change(Reserve, :count).by(1)
      end

      it "redirects to the created reserf" do
        post reserves_url, params: { reserf: valid_attributes }
        expect(response).to redirect_to(reserf_url(Reserve.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Reserve" do
        expect {
          post reserves_url, params: { reserf: invalid_attributes }
        }.to change(Reserve, :count).by(0)
      end

      it "renders a successful response (i.e. to display the 'new' template)" do
        post reserves_url, params: { reserf: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested reserf" do
        reserve = Reserve.create! valid_attributes
        patch reserf_url(reserve), params: { reserf: new_attributes }
        reserve.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the reserf" do
        reserve = Reserve.create! valid_attributes
        patch reserf_url(reserve), params: { reserf: new_attributes }
        reserve.reload
        expect(response).to redirect_to(reserf_url(reserve))
      end
    end

    context "with invalid parameters" do
      it "renders a successful response (i.e. to display the 'edit' template)" do
        reserve = Reserve.create! valid_attributes
        patch reserf_url(reserve), params: { reserf: invalid_attributes }
        expect(response).to be_successful
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested reserf" do
      reserve = Reserve.create! valid_attributes
      expect {
        delete reserf_url(reserve)
      }.to change(Reserve, :count).by(-1)
    end

    it "redirects to the reserves list" do
      reserve = Reserve.create! valid_attributes
      delete reserf_url(reserve)
      expect(response).to redirect_to(reserves_url)
    end
  end
end
